// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240119134641_LeaveBalanceEntityAdded")]
    partial class LeaveBalanceEntityAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateOnly>("JoinedDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("FamilyDays")
                        .HasColumnType("integer");

                    b.Property<int>("FamilyDaysTaken")
                        .HasColumnType("integer");

                    b.Property<int>("RemoteWorkDays")
                        .HasColumnType("integer");

                    b.Property<int>("RemoteWorkDaysTaken")
                        .HasColumnType("integer");

                    b.Property<int>("SickDays")
                        .HasColumnType("integer");

                    b.Property<int>("SickDaysTaken")
                        .HasColumnType("integer");

                    b.Property<int>("VacationDays")
                        .HasColumnType("integer");

                    b.Property<int>("VacationDaysTaken")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("API.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveRequestId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaveReviewerId")
                        .HasColumnType("integer");

                    b.Property<string>("LeaveStatus")
                        .HasColumnType("text");

                    b.Property<int>("LeaveSubmitterId")
                        .HasColumnType("integer");

                    b.Property<string>("LeaveType")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("LeaveReviewerId");

                    b.HasIndex("LeaveSubmitterId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("API.Entities.LeaveBalance", b =>
                {
                    b.HasOne("API.Entities.AppUser", "Employee")
                        .WithOne("LeaveBalance")
                        .HasForeignKey("API.Entities.LeaveBalance", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API.Entities.LeaveRequest", b =>
                {
                    b.HasOne("API.Entities.AppUser", "LeaveReviewer")
                        .WithMany("LeaveRequestReviewed")
                        .HasForeignKey("LeaveReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "LeaveSubmitter")
                        .WithMany("LeaveRequestCreated")
                        .HasForeignKey("LeaveSubmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveReviewer");

                    b.Navigation("LeaveSubmitter");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("LeaveBalance");

                    b.Navigation("LeaveRequestCreated");

                    b.Navigation("LeaveRequestReviewed");
                });
#pragma warning restore 612, 618
        }
    }
}
